name: CPE Dictionary Test

on: [push, pull_request]
  paths:
    - 'csaf_2.0/*'

jobs:
  cpe-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Perform CPE Dictionary Test
      run: ./csaf_2.0/test/cpe/run_tests.sh
